service: contact-form-api

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  httpApi:
    cors:
      allowedOrigins:
        - https://contact-form-client-kappa.vercel.app
      allowedMethods:
        - POST
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
      allowCredentials: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"
  environment:
    TO_EMAIL: edielton.dantas@hotmail.com
    FROM_EMAIL: edielton.dantas@hotmail.com

functions:
  sendEmail:
    handler: handler.sendEmail
    events:
      - httpApi:
          path: /contact
          method: POST

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3003
